# Generated by Django 5.2.8 on 2026-01-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0002_alter_order_created_at_alter_order_order_number_and_more'),
        ('products', '0002_alter_category_is_active_alter_product_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryreservation',
            name='expires_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='inventoryreservation',
            index=models.Index(fields=['product', 'expires_at'], name='inventory_i_product_46b243_idx'),
        ),
    ]
