import factory
from factory.django import DjangoModelFactory
from factory import Faker, SubFactory, LazyAttribute
from .models import Payment
from apps.orders.factories import OrderFactory


class PaymentFactory(DjangoModelFactory):
    class Meta:
        model = Payment
    
    order = SubFactory(OrderFactory)
    # reference will be auto-generated by the model's save() method
    amount = LazyAttribute(lambda obj: obj.order.total_amount)
    currency = 'ETB'
    status = Payment.PaymentStatus.PENDING
    provider = 'chapa'
    raw_response = factory.LazyFunction(lambda: {
        'message': 'Payment initiated',
        'status': 'pending'
    })
